### ISSUE TITLE
spot doesn't build on FreeBSD 13.1 amd64

### ISSUE THREAD

**Issue by duncan-bayne** [xou816/spot#543]
**Describe the bug**
When attempting to build spot on FreeBSD 13.1, I receive an error `AttributeError: 'NoneType' object has no attribute 'has_header'`.

**To Reproduce**
```
git clone https://github.com/xou816/spot
cd spot
meson target -Dbuildtype=debug -Doffline=false --prefix="$HOME/.local"
```

**Expected behavior**
I'd expect spot to build without errors, as on e.g. Mobian GNU/Linux (I run it happily on my PinePhone, built from source :) ).

**General information:**
* This is a native build.
* FreeBSD 13.1 RELEASE generic amd64
* Python 3.9.13
* meson 0.62.2
* ninja 1.10.2

**Stack trace:**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 153, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/msetup.py", line 301, in run
    app.generate()
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/msetup.py", line 185, in generate
    self._generate(env)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/msetup.py", line 229, in _generate
    intr.run()
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 2724, in run
    super().run()
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 149, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 180, in evaluate_statement
    return self.function_call(cur)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 455, in function_call
    res = func(node, func_args, kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 574, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 2218, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 180, in evaluate_statement
    return self.function_call(cur)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 455, in function_call
    res = func(node, func_args, kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 5 more times]
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 109, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 127, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 1638, in func_dependency
    d = df.lookup(kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreter/dependencyfallbacks.py", line 352, in lookup
    dep = func(kwargs, func_args, func_kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreter/dependencyfallbacks.py", line 93, in _do_dependency
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/dependencies/detect.py", line 112, in find_external_dependency
    d = c()
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/dependencies/factory.py", line 105, in <lambda>
    DependencyMethods.SYSTEM:         lambda env, kwargs: system_class(name, env, kwargs),
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/dependencies/misc.py", line 529, in __init__
    if not self.clib_compiler.has_header('openssl/ssl.h', '', env)[0]:
AttributeError: 'NoneType' object has no attribute 'has_header'
The Meson build system
Version: 0.62.2
Source dir: /usr/home/duncan/freebsd-setup/spot
Build dir: /usr/home/duncan/freebsd-setup/spot/target
Build type: native build
Project name: spot
Project version: 0.3.3
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program glib-compile-schemas found: YES (/usr/local/bin/glib-compile-schemas)
Program appstream-util found: NO
Program msgfmt found: YES (/usr/local/bin/msgfmt)
Program msginit found: YES (/usr/local/bin/msginit)
Program msgmerge found: YES (/usr/local/bin/msgmerge)
Program xgettext found: YES (/usr/local/bin/xgettext)
Found pkg-config: /usr/local/bin/pkg-config (1.8.0)
Run-time dependency libadwaita-1 found: YES 1.1.0
Run-time dependency gtk4 found: YES 4.6.3
Run-time dependency glib-2.0 found: YES 2.72.2

src/meson.build:6:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**Additional context**
I've reported the Meson behaviour above as https://github.com/mesonbuild/meson/issues/10666.

**Comment by Diegovsky** [comment]
I would love to get this working on FreeBSD :)

I don't have it installed though, would you be willing to help with that?

**Comment by duncan-bayne** [comment]
Yeah aboslutely @Diegovsky!  What sort of help would be useful?  Even if it's just providing a FreeBSD dev environment, I can do that.

**Comment by Diegovsky** [comment]
Nice! I really appreciate the enthusiasm. Are you able to provide me a build environment? That would help a lot, also because I have no idea how BSDs work WRT package management and building projects :)

**Comment by duncan-bayne** [comment]
I've installed all build requirements on the FreeBSD instance, but it looks like there are some other issues preventing it from even getting this far.  E.g. `bash` on FreeBSD is in `/usr/local/bin` but the spot build files assume it's in `/bin`.

**Comment by duncan-bayne** [comment]
E.g. 

```
ec2-user@freebsd:~/spot $ ninja install -C target
ninja: Entering directory `target'
[0/2] Generating src/cargo-build with a custom command
/bin/sh: /bin/bash: not found
FAILED: src/spot 
/bin/bash /usr/home/ec2-user/spot/build-aux/cargo.sh /usr/home/ec2-user/spot /usr/home/ec2-user/spot/target spot src/spot debug '' false
ninja: build stopped: subcommand failed.
```

**Comment by Diegovsky** [comment]
> I've set up a small FreeBSD instance on AWS, please drop me an email at [duncan@bayne.id.au](mailto:duncan@bayne.id.au) and I'll arrange access.

E-mail dropped. Let's get to it :)

> I've installed all build requirements on the FreeBSD instance, but it looks like there are some other issues preventing it from even getting this far. E.g. bash on FreeBSD is in /usr/local/bin but the spot build files assume it's in /bin.

Oh that is a total no-no. Will look into these build scripts and even port them to posix of necessary.

**Comment by duncan-bayne** [comment]
@Diegovsky are you still interested in giving this a go?  The server is up and running, drop me an email at duncan@bayne.id.au for access.

**Comment by Diegovsky** [comment]
Yeah, sorry about that. I just got a bit of time from uni and will be working on it :)

**Comment by duncan-bayne** [comment]
Don't apologise!  I remember how hectic Uni was, if you have any time to work on it at all it'd be a miracle.

**Comment by Diegovsky** [comment]
Thank you for the patience! I tried to build on a FreeBSD 13.2-RC5 vm with success. Are you able to upgrade to it or should I investigate 13.1?

**Comment by Diegovsky** [comment]
@duncan-bayne just pinging again in case you forgot (I usually do)
